### ISSUE TITLE
Integrate Yii2 RBAC security and integrate User capability

### ISSUE THREAD

**Issue by kefahi** [kefahi/io#3]
Just as examples 
- [Yii2 Rback extension](https://github.com/dektrium/yii2-rbac)
- [User](https://github.com/dektrium/yii2-user)
- [Yii2 Admin](http://mdmsoft.github.io/yii2-admin/index.html)

Open to any other option as well.

**Comment by anini** [comment]
Used both [Yii2-rbac](https://github.com/dektrium/yii2-rbac) and [Yii2-user](https://github.com/dektrium/yii2-user).
