### ISSUE TITLE
Consider and implement the better User identity integration option

### ISSUE THREAD

**Issue by kefahi** [kefahi/io#5]
Using [Yii2 Authclient](https://github.com/yiisoft/yii2-authclient) enable OpenID/OAuth2 which offers integration with major identity integration providers such as Facebook, Google, Microsoft, Yahoo, Linkedin and Twitter.

Have a look at this [nice article](http://code.tutsplus.com/tutorials/programming-with-yii2-authclient-integration-with-twitter-google-and-other-networks--cms-23489).

**Comment by anini** [comment]
Used [Yii2 Authclient](https://github.com/yiisoft/yii2-authclient).
